#SPDX-License-Identifier: MIT-0
---
# tasks file for add_users

- name: Create user accounts
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    groups: sudo
    append: true
  loop: "{{ users_to_create }}"
  become: yes
