#SPDX-License-Identifier: MIT-0
---
# tasks file for setup_ssh_for_users

- name: Create .ssh directory
  file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0700'
  loop: "{{ users_to_create }}"
  become: yes

- name: Install SSH public key
  copy:
    content: "{{ ssh_public_key }}\n"
    dest: "/home/{{ item }}/.ssh/authorized_keys"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0600'
  loop: "{{ users_to_create }}"
  become: yes
